models/FormIssueFile.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;

/**
 * This is the model class for table "form_issue_file".
 *
 * @property int $id รหัสอัตโนมัติ
 * @property int $form_issue_id form issue
 * @property int $form_issue_submit_id form issue review
 * @property int $parent_id parent
 * @property int $type 1=รูปภาพ, 2=ไฟล์เอกสาร
 * @property string $name ชื่อเอกสาร/รูปภาพ
 * @property string $file_name ชื่อไฟล์ที่บันทึกในระบบ
 * @property int $deleted 0=ใช้งาน,1=ไม่ใช้งาน
 * @property int $created_by สร้างโดย
 * @property string $created_at สร้างเมื่อ
 * @property int $updated_by ปรับปรุงโดย
 * @property string $updated_at ปรับปรุงเมื่อ
 *
 * @property FormIssue $formIssue
 * @property FormIssueSubmit $formIssueSubmit
 * @property FormIssueFile $parent
 * @property FormIssueFile[] $formIssueFiles
 * @property User $createdBy
 * @property User $updatedBy
 */
class FormIssueFile extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    const TYPE_IMAGE = 1;
    const TYPE_FILE = 2;
    const SCENARIO_FILE = 'file';
    const SCENARIO_IMAGE = 'image';

    public $uploadFiles;

    public static function getTypeLabel() {
        return[
            self::TYPE_IMAGE => Yii::t('app', 'รูปภาพ'),
            self::TYPE_FILE => Yii::t('app', 'ไฟล์'),
        ];
    }

    public static function tableName() {
        return 'form_issue_file';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['form_issue_id', 'form_issue_submit_id', 'parent_id', 'type', 'deleted', 'created_by', 'updated_by'], 'integer'],
            [['name'], 'required', 'on' => self::SCENARIO_FILE],
            [['uploadFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => 'jpg, jpeg, png, gif', 'on' => self::SCENARIO_IMAGE],
            [['uploadFiles'], 'file', 'skipOnEmpty' => true, 'on' => self::SCENARIO_FILE],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'file_name'], 'string', 'max' => 255],
            [['form_issue_id'], 'exist', 'skipOnError' => true, 'targetClass' => FormIssue::className(), 'targetAttribute' => ['form_issue_id' => 'id']],
            [['form_issue_submit_id'], 'exist', 'skipOnError' => true, 'targetClass' => FormIssueSubmit::className(), 'targetAttribute' => ['form_issue_submit_id' => 'id']],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => FormIssueFile::className(), 'targetAttribute' => ['parent_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'รหัสอัตโนมัติ'),
            'form_issue_id' => Yii::t('app', 'form issue'),
            'form_issue_submit_id' => Yii::t('app', 'form issue review'),
            'parent_id' => Yii::t('app', 'parent'),
            'type' => Yii::t('app', '1=รูปภาพ, 2=ไฟล์เอกสาร'),
            'name' => Yii::t('app', 'ชื่อเอกสาร/รูปภาพ'),
            'file_name' => Yii::t('app', 'ชื่อไฟล์ที่บันทึกในระบบ'),
            'uploadFiles' => Yii::t('app', 'ไฟล์'),
            'deleted' => Yii::t('app', '0=ใช้งาน,1=ไม่ใช้งาน'),
            'created_by' => Yii::t('app', 'สร้างโดย'),
            'created_at' => Yii::t('app', 'สร้างเมื่อ'),
            'updated_by' => Yii::t('app', 'ปรับปรุงโดย'),
            'updated_at' => Yii::t('app', 'ปรับปรุงเมื่อ'),
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => function() {
                    return date('Y-m-d H:i:s');
                },
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormIssue() {
        return $this->hasOne(FormIssue::className(), ['id' => 'form_issue_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormIssueSubmit() {
        return $this->hasOne(FormIssueSubmit::className(), ['id' => 'form_issue_submit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent() {
        return $this->hasOne(FormIssueFile::className(), ['id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormIssueFiles() {
        return $this->hasMany(FormIssueFile::className(), ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy() {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy() {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    public function getFileIconClass() {
        $info = pathinfo($this->file_name);
        if (in_array($info['extension'], ['doc', 'docx'])) {
            return 'icon fa-file-word-o';
        } else if (in_array($info['extension'], ['pdf'])) {
            return 'icon fa-file-pdf-o';
        } else if (in_array($info['extension'], ['xls', 'xlsx'])) {
            return 'icon fa-file-excel-o';
        } else if (in_array($info['extension'], ['jpg', 'jpeg', 'gif', 'png'])) {
            return 'fa-file-image-o';
        } else {
            return 'icon fa-file-text-o';
        }
    }

    public function getFileUrl() {
        return Url::to("@web/{$this->file_name}", true);
    }

    public function getFilePath() {
        return Yii::getAlias("@app/web/{$this->file_name}");
    }

    public function getPath() {
        if ($this->type == self::TYPE_FILE) {
            return "uploads/six-month/files/{$this->form_issue_id}";
        } else {
            return "uploads/six-month/images/{$this->form_issue_id}";
        }
    }
    
    public function getPreviewType() {
        $info = pathinfo($this->fileUrl);
        if (in_array($info['extension'], ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'csv'])) {
            return 'office';
        } else if (in_array($info['extension'], ['tif', 'ai', 'eps'])) {
            return 'gdocs';
        } else if (in_array($info['extension'], ['txt'])) {
            return 'text';
        } else if (in_array($info['extension'], ['pdf'])) {
            return 'pdf';
        }
        return 'image';
    }

    public function getPreviewConfig() {
        $info = pathinfo($this->fileUrl);
        return [
            'caption' => $this->type == self::TYPE_FILE ? $this->name : $info['basename'],
            'key' => $this->id,
            'type' => $this->previewType,
            'size' => file_exists($this->filePath) ? filesize($this->filePath) : 0,
        ];
    }

    /**
     * {@inheritdoc}
     * @return FormIssueFileQuery the active query used by this AR class.
     */
    public static function find() {
        return new FormIssueFileQuery(get_called_class());
    }

}

controllers/FormIssueFileController.php
<?php

namespace app\controllers;

use Yii;
use app\models\FormIssueFile;
use app\models\FormIssueFileSearch;
//use app\rbac\RbacController;
use app\rbac\RbacController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use kartik\widgets\Alert;

/**
 * FormIssueFileController implements the CRUD actions for FormIssueFile model.
 */
class FormIssueFileController extends RbacController {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all FormIssueFile models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new FormIssueFileSearch();
        $searchModel->deleted = 0;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single FormIssueFile model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "FormIssueFile #" . $id,
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                Html::a(Yii::t('app', 'แก้ไข'), ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                        'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new FormIssueFile model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $request = Yii::$app->request;
        $model = new FormIssueFile();

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => Yii::t('app', "เพิ่ม FormIssueFile"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                $model = new FormIssueFile();
                Yii::$app->session->setFlash(Alert::TYPE_SUCCESS, Yii::t('app', 'เพิ่มข้อมูล form-issue-file เรียบร้อยแล้ว'));
                return [
                    'forceReload' => '#crud-datatable-form-issue-file-pjax',
                    'title' => Yii::t('app', "เพิ่ม FormIssueFile"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else {
                return [
                    'title' => Yii::t('app', "เพิ่ม FormIssueFile"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
             *   Process for non-ajax request
             */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                            'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing FormIssueFile model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => Yii::t('app', "แก้ไข") . " FormIssueFile #" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-form-issue-file-pjax',
                    'title' => Yii::t('app', "แก้ไข") . " FormIssueFile #" . $id,
                    'content' => '<div class="alert alert-success dark">' . Yii::t('app', 'แก้ไขข้อมูล form-issue-file เรียบร้อยแล้ว') . '</div>',
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a(Yii::t('app', 'แก้ไข'), ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
                ];
            } else {
                return [
                    'title' => Yii::t('app', "แก้ไข") . " FormIssueFile #" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
             *   Process for non-ajax request
             */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                            'model' => $model,
                ]);
            }
        }
    }

    public function actionDownload($key) {
        $model = $this->findModel($key);
        if (file_exists($model->filePath)) {
            $info = pathinfo($model->filePath);
//            \yii\helpers\VarDumper::dump($info);
//            exit;
            return Yii::$app->response->sendFile($model->filePath, isset($model->name) ? "{$model->name}.{$info['extension']}" : $info['basename']);
        }
    }

    /**
     * Delete an existing FormIssueFile model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete() {
        $request = Yii::$app->request;
        $model = $this->findModel($request->post('key'));
        $model->deleted = 1;
        $model->save();

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'forceReload' => '#form-issue-status-pjax',
            ];
        } else {
            /*
             *   Process for non-ajax request
             */
            return $this->redirect(['index']);
        }
    }

    /**
     * Delete multiple existing FormIssueFile model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete() {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-form-issue-file-pjax'];
        } else {
            /*
             *   Process for non-ajax request
             */
            return $this->redirect(['index']);
        }
    }

    /**

views/form-issue-file/_columns.php
<?php
use yii\helpers\Url;

return [
    //[
    //    'class' => 'kartik\grid\CheckboxColumn',
    //    'width' => '20px',
    //],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'form_issue_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'form_issue_submit_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'parent_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'type',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'file_name',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'deleted',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_by',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_by',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>Yii::t('app', 'รายละเอียด'),'data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>Yii::t('app', 'แก้ไข'), 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>Yii::t('app', 'ลบ'), 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title' => Yii::t('app', 'ยืนยันการลบ'),
                          'data-confirm-message' => Yii::t('app', 'ต้องการลบรายการนี้ใช่หรือไม่ ?'),
                          'data-confirm-ok' => Yii::t('app', 'ใช่'),
                          'data-confirm-cancel' => Yii::t('app', 'ไม่'),
        ],
    ],

];   

views/form-issue-file/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FormIssueFile */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-issue-file-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $this->renderFile('@app/views/widgets/_alert.php'); ?>

    <?= $form->field($model, 'form_issue_id')->textInput() ?>

    <?= $form->field($model, 'form_issue_submit_id')->textInput() ?>

    <?= $form->field($model, 'parent_id')->textInput() ?>

    <?= $form->field($model, 'type')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'file_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deleted')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_by')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/form-issue-file/_search.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FormIssueFile */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-issue-file-search">

    <?php $form = ActiveForm::begin([
        'action' => Url::to(['form-issue-file/index']),
        'method' => 'get',
        'options' => [
            'data-pjax' => 1,
        ],
        'type' => ActiveForm::TYPE_INLINE,
    ]); ?>
    
    <?= $form->field($model, 'form_issue_id') ?>

    <?= $form->field($model, 'form_issue_submit_id') ?>

    <?= $form->field($model, 'parent_id') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'file_name') ?>

    <?= $form->field($model, 'deleted') ?>

    <?= $form->field($model, 'created_by') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_by') ?>

    <?= $form->field($model, 'updated_at') ?>

  
	<div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'ค้นหา'), ['class' => 'btn btn-primary']) ?>
        </div>

    <?php ActiveForm::end(); ?>
    
</div>

views/form-issue-file/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\FormIssueFile */

?>
<div class="form-issue-file-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/form-issue-file/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FormIssueFileSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Form Issue Files');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="form-issue-file-index">
    <div class="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable-form-issue-file',
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'floatHeader' => true,
            'floatHeaderOptions' => ['top' => 66],
            'pjax'=>true,
            'pjaxSettings' => [
                'beforeGrid' => $this->render('_search', ['model'=>$searchModel]),
            ],
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar' => [
                [
                    'options' => [
                        'class' => '',
                    ],
                    'content' =>
                    Html::a('<i class="glyphicon glyphicon-plus"></i> ' .Yii::t('app', 'เพิ่ม') . Yii::t('app', 'Form Issue Files'), ['create'], ['role' => 'modal-remote', 'class' => 'btn btn-success btn-raised']) .
                    Html::a('<i class="glyphicon glyphicon-repeat"></i> ' .Yii::t('app', 'โหลดใหม่'), Url::current(), ['data-pjax' => 1, 'class' => 'btn btn-default btn-raised'])
                ],
            ],    
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'type' => 'primary',
                'heading' => FALSE,
                'before' => '<div class="pull-left">{summary}</div>',
//                'after' => FALSE,
//                'footer' => FALSE,
            ],
            'pager' => array(
                'firstPageLabel' => '<i class="icon md-skip-previous"></i>',
                'lastPageLabel' => '<i class="icon md-skip-next"></i>',
                'prevPageLabel' => '<i class="icon md-fast-rewind"></i>',
                'nextPageLabel' => '<i class="icon md-fast-forward"></i>',
            ),
        ])?>
    </div>
</div>

views/form-issue-file/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\FormIssueFile */
?>
<div class="form-issue-file-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/form-issue-file/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\FormIssueFile */
?>
<div class="form-issue-file-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'form_issue_id',
            'form_issue_submit_id',
            'parent_id',
            'type',
            'name',
            'file_name',
            'deleted',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
        ],
    ]) ?>

</div>