models/YearlyAssessment.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "yearly_assessment".
 *
 * @property int $id รหัสอัตโนมัติ
 * @property int $office_id หน่วยงาน
 * @property int $year ปี
 * @property string $garbage_prev garbage_prev
 * @property string $garbage_cur garbage_cur
 * @property string $bag_prev bag_prev
 * @property string $bag_cur bag_cur
 * @property string $cup_prev cup_prev
 * @property string $cup_cur cup_cur
 * @property string $foam_prev foam_prev
 * @property string $foam_cur foam_cur
 * @property string $garbage_percent garbage_percent
 * @property string $bag_percent bag_percent
 * @property string $cup_percent cup_percent
 * @property string $foam_percent foam_percent
 * @property string $garbage_score garbage_score
 * @property string $bag_score bag_score
 * @property string $cup_score cup_score
 * @property string $foam_score foam_score
 * @property string $plus_score plus_score
 * @property string $minus_score minus_score
 * @property string $total_score total_score
 * @property int $confirmed_by ยืนยันข้อมูลโดย
 * @property string $confirmed_at ยืนยันข้อมูลเมื่อ
 * @property int $status สถานะ
 * @property string $population_total จำนวนบุคคลากร
 * @property int $deleted 0=ใช้งาน,1=ไม่ใช้งาน
 * @property int $created_by สร้างโดย
 * @property string $created_at สร้างเมื่อ
 * @property int $updated_by ปรับปรุงโดย
 * @property string $updated_at ปรับปรุงเมื่อ
 * @property int $pop_int จำนวนบุคคลากรภายใน(คน) 
 * @property int $pop_ext จำนวนบุคคลากรภายนอก(คน) 
 * @property int $office_population จำนวนบุคคลากรในหน่วยงาน(คน) 
 * @property int $work_day จำนวนวันทำงาน(วัน) 
 * @property string $garbage ปริมาณขยะมูลฝอย (กก.) 
 * @property string $bag จำนวนถุงพลาสติก (ใบ) 
 * @property string $cup จำนวนแก้วพลาสติก (ใบ) 
 * @property string $mask  
 * @property string $mask_score
 * @property string $mask_percent 
 * @property string $mask_cur 
 * @property string $mask_prev 
 *
 * @property Office $office
 * @property User $confirmedBy
 * @property User $createdBy
 * @property User $updatedBy
 */
class YearlyAssessment extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'yearly_assessment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['office_id', 'year', 'confirmed_by', 'status', 'deleted', 'created_by', 'updated_by', 'pop_int', 'pop_ext', 'office_population', 'work_day'], 'integer'],
            [['garbage_prev', 'garbage_cur', 'bag_prev', 'bag_cur', 'cup_prev', 'cup_cur', 'foam_prev', 'foam_cur', 'garbage_percent', 'bag_percent', 'cup_percent', 'foam_percent', 'garbage_score', 'bag_score', 'cup_score', 'foam_score', 'plus_score', 'minus_score', 'total_score', 'population_total', 'garbage', 'bag', 'cup', 'foam', 'mask', 'mask_score', 'mask_percent', 'mask_cur', 'mask_prev'], 'number'],
            [['confirmed_at', 'created_at', 'updated_at'], 'safe'],
            [['office_id'], 'exist', 'skipOnError' => true, 'targetClass' => Office::className(), 'targetAttribute' => ['office_id' => 'id']],
            [['confirmed_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['confirmed_by' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'รหัสอัตโนมัติ'),
            'office_id' => Yii::t('app', 'หน่วยงาน'),
            'year' => Yii::t('app', 'ปี'),
            'garbage_prev' => Yii::t('app', 'garbage_prev'),
            'garbage_cur' => Yii::t('app', 'garbage_cur'),
            'bag_prev' => Yii::t('app', 'bag_prev'),
            'bag_cur' => Yii::t('app', 'bag_cur'),
            'cup_prev' => Yii::t('app', 'cup_prev'),
            'cup_cur' => Yii::t('app', 'cup_cur'),
            'foam_prev' => Yii::t('app', 'foam_prev'),
            'mask_prev' => Yii::t('app', 'mask_prev'),
            'foam_cur' => Yii::t('app', 'foam_cur'),
            'mask_cur' => Yii::t('app', 'mask_cur'),
            'garbage_percent' => Yii::t('app', 'garbage_percent'),
            'bag_percent' => Yii::t('app', 'bag_percent'),
            'cup_percent' => Yii::t('app', 'cup_percent'),
            'foam_percent' => Yii::t('app', 'foam_percent'),
            'mask_percent' => Yii::t('app', 'mask_percent'),
            'garbage_score' => Yii::t('app', 'คะแนนขยะ'),
            'bag_score' => Yii::t('app', 'คะแนนถุง'),
            'cup_score' => Yii::t('app', 'คะแนนแก้ว'),
            'foam_score' => Yii::t('app', 'คะแนนโฟม'),
            'mask_score' => Yii::t('app', 'คะแนนหน้ากากอนามัย'),
            'plus_score' => Yii::t('app', 'บวกคะแนน'),
            'minus_score' => Yii::t('app', 'ลบคะแนน'),
            'total_score' => Yii::t('app', 'รวมคะแนน'),
            'confirmed_by' => Yii::t('app', 'ยืนยันข้อมูลโดย'),
            'confirmed_at' => Yii::t('app', 'ยืนยันข้อมูลเมื่อ'),
            'status' => Yii::t('app', 'สถานะ'),
            'population_total' => Yii::t('app', 'จำนวนบุคคลากร'),
            'deleted' => Yii::t('app', '0=ใช้งาน,1=ไม่ใช้งาน'),
            'created_by' => Yii::t('app', 'สร้างโดย'),
            'created_at' => Yii::t('app', 'สร้างเมื่อ'),
            'updated_by' => Yii::t('app', 'ปรับปรุงโดย'),
            'updated_at' => Yii::t('app', 'ปรับปรุงเมื่อ'),
            'pop_int' => Yii::t('app', 'จำนวนบุคคลากรภายใน(คน)'),
            'pop_ext' => Yii::t('app', 'จำนวนบุคคลากรภายนอก(คน)'),
            'office_population' => Yii::t('app', 'จำนวนบุคคลากรในหน่วยงาน(คน)'),
            'work_day' => Yii::t('app', 'จำนวนวันทำงาน(วัน)'),
            'garbage' => Yii::t('app', 'ปริมาณขยะมูลฝอย (กก.)'),
            'bag' => Yii::t('app', 'จำนวนถุงพลาสติก (ใบ)'),
            'cup' => Yii::t('app', 'จำนวนแก้วพลาสติก (ใบ)'),
            'foam' => Yii::t('app', 'จำนวนโฟมบรรจุอาหาร (ใบ)'),
            'mask' => Yii::t('app', 'จำนวนหน้ากากอนามัย (ชิ้น)'),
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => function() {
                    return date('Y-m-d H:i:s');
                },
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffice() {
        return $this->hasOne(Office::className(), ['id' => 'office_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConfirmedBy() {
        return $this->hasOne(User::className(), ['id' => 'confirmed_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy() {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy() {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * {@inheritdoc}
     * @return YearlyAssessmentQuery the active query used by this AR class.
     */
    public static function find() {
        return new YearlyAssessmentQuery(get_called_class());
    }

    public static function getAssessmentStatusLabels() {
        return [
            0 => 'ยังไม่ประเมิน',
            1 => 'ประเมินแล้ว',
        ];
    }

}

controllers/YearlyAssessmentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\YearlyAssessment;
use app\models\YearlyAssessmentSearch;
//use yii\web\Controller;
use app\rbac\RbacController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use kartik\widgets\Alert;

/**
 * YearlyAssessmentController implements the CRUD actions for YearlyAssessment model.
 */
class YearlyAssessmentController extends RbacController {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all YearlyAssessment models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new YearlyAssessmentSearch();
        $searchModel->deleted = 0;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single YearlyAssessment model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $request = Yii::$app->request;
        $ya = $this->findModel($id);
        $year = $ya->year;
        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "ผลการดำเนินการ ปีงบประมาณ {$year}",
                'content' => $this->renderAjax('@app/views/site/_yearly-assessment', [
                    'year' => $year,
                    'ya' => $ya,
                ]),
                'footer' => Html::button(Yii::t('app', "ปิด"), ['class' => 'btn btn-default pull-left btn-lg', 'data-dismiss' => "modal"])
            ];
        } else {
            /*
             *   Process for non-ajax request
             */
            return $this->render('@app/views/site/yearly-assessment', [
                        'year' => $year,
                        'ya' => $ya,
            ]);
        }
    }

    /**
     * Creates a new YearlyAssessment model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $request = Yii::$app->request;
        $model = new YearlyAssessment();

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => Yii::t('app', "เพิ่ม YearlyAssessment"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                $model = new YearlyAssessment();
                Yii::$app->session->setFlash(Alert::TYPE_SUCCESS, Yii::t('app', 'เพิ่มข้อมูล yearly-assessment เรียบร้อยแล้ว'));
                return [
                    'forceReload' => '#crud-datatable-yearly-assessment-pjax',
                    'title' => Yii::t('app', "เพิ่ม YearlyAssessment"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else {
                return [
                    'title' => Yii::t('app', "เพิ่ม YearlyAssessment"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
             *   Process for non-ajax request
             */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                            'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing YearlyAssessment model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => Yii::t('app', "แก้ไข") . " YearlyAssessment #" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-yearly-assessment-pjax',
                    'title' => Yii::t('app', "แก้ไข") . " YearlyAssessment #" . $id,
                    'content' => '<div class="alert alert-success dark">' . Yii::t('app', 'แก้ไขข้อมูล yearly-assessment เรียบร้อยแล้ว') . '</div>',
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a(Yii::t('app', 'แก้ไข'), ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
                ];
            } else {
                return [
                    'title' => Yii::t('app', "แก้ไข") . " YearlyAssessment #" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
             *   Process for non-ajax request
             */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                            'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing YearlyAssessment model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $model->deleted = 1;
        if (!$model->save()) {
            Yii::$app->session->setFlash(Alert::TYPE_DANGER, Yii::t('app', "ไม่สามารถลบข้อมูลได้ {error}", [
                        'error' => \Yii::$app->util->errorSummary($model),
            ]));
            if ($request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return [
                    'forceReload' => '#crud-datatable-yearly-assessment-pjax',
                    'title' => Yii::t('app', 'เกิดข้อผิดพลาด'),
                    'content' => $this->renderAjax('@app/views/widgets/_alert'),
                    'footer' => Html::button(Yii::t('app', "ปิด"), ['class' => 'btn btn-default pull-left btn-lg', 'data-dismiss' => "modal"])
                ];
            } else {
                return $this->redirect(['index']);
            }
        }

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-yearly-assessment-pjax'];
        } else {
            /*
             *   Process for non-ajax request
             */
            return $this->redirect(['index']);
        }
    }

    /**
     * Delete multiple existing YearlyAssessment model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete() {
        $request = Yii::$app->request;

views/yearly-assessment/_assess.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\YearlyAssessment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="yearly-assessment-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $this->renderFile('@app/views/widgets/_alert.php'); ?>

    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'garbage_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'readonly' => true,
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => false,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'bag_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'readonly' => true,
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => false,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'cup_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'readonly' => true,
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => false,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'foam_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'readonly' => true,
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => false,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'plus_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'onkeyup' => new JsExpression('calculateScore()'),
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => false,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'minus_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'onkeyup' => new JsExpression('calculateScore()'),
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => false,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'total_score')->widget(MaskedInput::class, [
                'options' => [
                    'class' => 'form-control',
                    'readonly' => true,
                ],
                'clientOptions' => [
                    'alias' => 'numeric',
                    'digits' => 0,
                    'prefix' => '',
                    'groupSeparator' => ',',
                    'allowMinus' => true,
                    'autoGroup' => true,
                    'autoUnmask' => true,
                    'unmaskAsNumber' => true,
                ]
            ]) ?>
        </div>
    </div>
    <?php
    $rc = $model->office->getReConfirmedMonthlyNumber($model->year);
    $lc = $model->office->getLateConfirmedMonthlyNumber($model->year);
    $fl = $model->office->getTotalFailedMonthlyNumber($model->year);
    ?>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-condensed table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">แก้ไข</th>
                        <th class="text-center">เกินกำหนด</th>
                        <th class="text-center">ตีกลับ</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-right"><?= Yii::$app->formatter->asDecimal($rc, 0); ?></td>
                        <td class="text-right"><?= Yii::$app->formatter->asDecimal($lc, 0); ?></td>
                        <td class="text-right"><?= Yii::$app->formatter->asDecimal($fl, 0); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive" style="height: calc(100vh - 400px);">
            <?=
            $this->renderFile('@app/views/site/_yearly-assessment.php', [
                'ya' => $model,
                'year' => $model->year,
            ]);
            ?>
            </div>
        </div>
    </div>
    <?php if (!Yii::$app->request->isAjax) { ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/yearly-assessment/_search.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use kartik\form\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\widgets\Select2;
use app\models\Role;
use app\models\YearlyAssessment;

/* @var $this yii\web\View */
/* @var $model app\models\YearlyAssessment */
/* @var $form yii\widgets\ActiveForm */
$currentRole = Yii::$app->session->get('currentRole');
?>

<div class="yearly-assessment-search margin-bottom-10">

    <?php
    $form = ActiveForm::begin([
                'action' => Url::to(['yearly-assessment/index']),
                'method' => 'get',
                'options' => [
                    'data-pjax' => 1,
                ],
                'type' => ActiveForm::TYPE_INLINE,
    ]);
    ?>
    <?php
    $data = ArrayHelper::map(Yii::$app->user->identity->person->getTotalResponsibleOffices(), 'id', 'typeName');

//    \yii\helpers\VarDumper::dump($data, 10, TRUE);
    echo $form->field($model, 'office_id', [
        'options' => [
            'style' => 'width: 300px',
            'class' => 'form-group',
        ]
    ])->widget(Select2::classname(), [
        'data' => $data,
        'options' => ['placeholder' => 'หน่วยงาน'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>
    <?= $form->field($model, 'year')->textInput(['type' => 'number']) ?>

    <?php
    
    if ($currentRole['role_id'] == Role::SUPER_ADMINISTRATOR || $currentRole['role_id'] == Role::REVIEWER ) {
        $data = ArrayHelper::map(\app\models\OfficeType::find()->orderBy('CONVERT(office_type.name USING TIS620) ASC')->all(), 'id', 'name');
//    \yii\helpers\VarDumper::dump($data, 10, TRUE);
        echo $form->field($model, 'officeType')->dropDownList($data, ['prompt' => 'ประเภทหน่วยงาน']);

        echo $form->field($model, 'level')->dropDownList(Yii::$app->util->getLevelLabels(), ['prompt' => 'ระดับหน่วยงาน']);
    }
    ?>
    <?php
    echo $form->field($model, 'isAssessed')->dropDownList(YearlyAssessment::getAssessmentStatusLabels(), ['prompt' => 'สถานะการประเมิน']);
    ?>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'ค้นหา'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/yearly-assessment/assess.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\YearlyAssessment */

?>
<div class="yearly-assessment-assess">
    <?= $this->render('_assess', [
        'model' => $model,
    ]) ?>
</div>

views/yearly-assessment/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\YearlyAssessment */

?>
<div class="yearly-assessment-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/yearly-assessment/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\YearlyAssessment */
?>
<div class="yearly-assessment-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>