controllers/MonthlyFormSubmitController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MonthlyFormSubmit;
use app\models\MonthlyFormSubmitSearch;
//use app\rbac\RbacController;
use app\rbac\RbacController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use kartik\widgets\Alert;
use yii\web\HttpException;
use app\models\MonthlyForm;
use app\models\OfficePopulationH;
use app\models\CalculationQueue;
use app\models\Setting;
use yii\helpers\Url;

/**
 * MonthlyFormSubmitController implements the CRUD actions for MonthlyFormSubmit model.
 */
class MonthlyFormSubmitController extends RbacController {
    protected $allowedActions = ['checked-list', 'check'];

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all MonthlyFormSubmit models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new MonthlyFormSubmitSearch();
        $searchModel->deleted = 0;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MonthlyFormSubmit model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => \Yii::t('app', "รานงานรายเดือน"),
                'size' => 'large',
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                    'redirect' => Url::to(['monthly-form-submit/view', 'id' => $id, 'file' => 1], true),
                    'file' => isset($file) ? $file : null,
                    'from' => 'view',
                ]),
                'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('view', [
                        'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new MonthlyFormSubmit model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($year, $month, $reload = null) {
        if (!isset(\Yii::$app->user->identity->person->office->officePopulationH)) {
            throw new HttpException(500, \Yii::t('app', 'กรุณาระบุข้อมูลบุคลากรในหน่วยงานของท่านก่อน'));
        }
        $request = Yii::$app->request;
        $model = MonthlyFormSubmit::find()->isDeleted(false)->year($year)->month($month)->office(\Yii::$app->user->identity->person->office_id)->last()->one();

        if (!isset($model)) {
            $model = new MonthlyFormSubmit();
            $model->year = $year;
            $model->month = $month;
            $model->office_id = \Yii::$app->user->identity->person->office_id;
            if (isset(\Yii::$app->user->identity->person->office->officePopulationH)) {
                $model->pop_int = \Yii::$app->user->identity->person->office->officePopulationH->pop_int;
                $model->pop_ext = \Yii::$app->user->identity->person->office->officePopulationH->pop_ext;
            }
        }

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => Yii::t('app', "บันทึกรายงานรายเดือน"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->validate()) {
                $model->office_population = $model->pop_int + $model->pop_ext;
                if (isset($model->confirmed_by)) {
                    $attrs = $model->attributes;
                    $model = new MonthlyFormSubmit();
                    $model->attributes = $attrs;
                    $model->confirmed_by = null;
                    $model->confirmed_at = null;
                    $model->checked_by = null;
                    $model->checked_at = null;
                    $model->is_pass = 0;
                    $model->is_late = 0;
                    $model->comment = null;
                }

                $model->submitted_by = \Yii::$app->user->id;
                $model->submitted_at = date('Y-m-d H:i:s');
                $model->save();
                if (!isset($reload)) {
                    $reload = '#crud-datatable-monthly-form-submit-pjax';
                }
                \app\models\Alert::addMonthlyConfirmAlert($model);
                return [
                    'forceReload' => $reload,
                    'title' => Yii::t('app', "บันทึกรายงานรายเดือน"),
                    'content' => '<div class="alert alert-success dark">' . Yii::t('app', 'บันทึกรายงานรายเดือนเรียบร้อยแล้ว') . '</div>',
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
                ];
            } else {
                return [
                    'title' => Yii::t('app', "บันทึกรายงานรายเดือน"),
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
             *   Process for non-ajax request
             */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                            'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing MonthlyFormSubmit model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
             *   Process for ajax request
             */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => Yii::t('app', "แก้ไข") . " MonthlyFormSubmit #" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-monthly-form-submit-pjax',
                    'title' => Yii::t('app', "แก้ไข") . " MonthlyFormSubmit #" . $id,
                    'content' => '<div class="alert alert-success dark">' . Yii::t('app', 'แก้ไขข้อมูล monthly-form-submit เรียบร้อยแล้ว') . '</div>',
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a(Yii::t('app', 'แก้ไข'), ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
                ];
            } else {
                return [
                    'title' => Yii::t('app', "แก้ไข") . " MonthlyFormSubmit #" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(Yii::t('app', 'ปิด'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
             *   Process for non-ajax request
             */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                            'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing MonthlyFormSubmit model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $request = Yii::$app->request;

views/monthly-form-submit/_columns-record-list.php
<?php

use yii\helpers\Url;

$items = [
    //[
    //    'class' => 'kartik\grid\CheckboxColumn',
    //    'width' => '20px',
    //],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
        'headerOptions' => [
            'style' => 'display: none;',
        ]
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'pop_int',
        'format' => ['decimal', 0],
        'header' => 'ภายใน',
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'pop_ext',
        'format' => ['decimal', 0],
        'header' => 'ภายนอก',
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'office_population',
        'format' => ['decimal', 0],
        'header' => 'ทั้งหมด',
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'work_day',
        'format' => ['decimal', 0],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'garbage',
        'format' => ['decimal', 2],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'bag',
        'format' => ['decimal', 0],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'cup',
        'format' => ['decimal', 0],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
        'hAlign' => 'right',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'foam',
        'format' => ['decimal', 0],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
        'hAlign' => 'right',
    ]
];
if ($searchModel->year == '2565') {
    $items[] = [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'mask',
        'format' => ['decimal', 0],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
        'hAlign' => 'right',
    ];
}


$items = array_merge($items, [
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'statusBadge',
        'format' => 'raw',
        'headerOptions' => [
            'style' => 'display: none;',
        ],
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'confirmed_at',
        'format' => ['date', 'php:d/m/Y'],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'checked_at',
        'format' => ['date', 'php:d/m/Y'],
        'headerOptions' => [
            'style' => 'display: none;',
        ],
    ]
        ]);
return $items;

views/monthly-form-submit/_compare.php
<?php
$lastYearForm = $model->lastYearForm;
?>
<table class="table table-bordered table-striped table-condensed">
    <tbody>
        <tr>
            <td class="font-weight-900">ปี</td>
            <td class="bg-green-600 white text-center"><?= $model->year ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= $lastYearForm->year ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">เดือน</td>
            <td class="bg-green-600 white text-center"><?= $model->monthName ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= $lastYearForm->monthName ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">การเก็บข้อมูล</td>
            <td class="bg-green-600 white text-center"><?= $model->sourceType->name ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= $lastYearForm->sourceType->name ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">จำนวนวันทำงาน(วัน)</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->work_day, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->work_day, 0) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">จำนวนบุคลากรภายใน</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->pop_int, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->pop_int, 0) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">จำนวนบุคลากรภายนอก</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->pop_ext, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->pop_ext, 0) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">รวมบุคลากร</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->office_population, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->office_population, 0) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ปริมาณขยะมูลฝอย (กก.)</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->garbage, 2) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->garbage, 2) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">จำนวนถุงพลาสติก (ใบ)</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->bag, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->bag, 0) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">จำนวนแก้วพลาสติก (ใบ)</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->cup, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->cup, 0) ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">จำนวนโฟมบรรจุอาหาร (ใบ)</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->foam, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->foam, 0) ?></td>
            <?php endif; ?>
        </tr>
        <?php if($model->year == '2565'){?>
        <tr>
            <td class="font-weight-900">จำนวนหน้ากากอนามัย (ชิ้น)</td>
            <td class="bg-green-600 white text-center"><?= Yii::$app->formatter->asDecimal($model->mask, 0) ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= Yii::$app->formatter->asDecimal($lastYearForm->mask, 0) ?></td>
            <?php endif; ?>
        </tr>
        <?php } ?>
        <tr>
            <td class="font-weight-900">หมายเหตุ</td>
            <td class="bg-green-600 white text-center"><?= $model->remark ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= $lastYearForm->remark ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ส่งล่าสุดโดย</td>
            <td class="bg-green-600 white text-center"><?= isset($model->submittedBy) ? $model->submittedBy->person->fullName : '' ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= isset($lastYearForm->submittedBy) ? $lastYearForm->submittedBy->person->fullName : '' ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ส่งล่าสุดวันที่</td>
            <td class="bg-green-600 white text-center"><?= isset($model->submitted_at) ? Yii::$app->thaiFormatter->asDate($model->submitted_at, 'php:d/m/Y') : '' ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= isset($lastYearForm->submitted_at) ? Yii::$app->thaiFormatter->asDate($lastYearForm->submitted_at, 'php:d/m/Y') : '' ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ยืนยันล่าสุดโดย</td>
            <td class="bg-green-600 white text-center"><?= isset($model->confirmedBy) ? $model->confirmedBy->person->fullName : '' ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= isset($lastYearForm->confirmedBy) ? $lastYearForm->confirmedBy->person->fullName : '' ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ยืนยันล่าสุดวันที่</td>
            <td class="bg-green-600 white text-center"><?= isset($model->confirmed_at) ? Yii::$app->thaiFormatter->asDate($model->confirmed_at, 'php:d/m/Y') : '' ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= isset($lastYearForm->confirmed_at) ? Yii::$app->thaiFormatter->asDate($lastYearForm->confirmed_at, 'php:d/m/Y') : '' ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ตรวจสอบล่าสุดโดย</td>
            <td class="bg-green-600 white text-center"><?= isset($model->checkedBy) ? $model->checkedBy->person->fullName : '' ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= isset($lastYearForm->checkedBy) ? $lastYearForm->checkedBy->person->fullName : '' ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">ตรวจสอบล่าสุดวันที่</td>
            <td class="bg-green-600 white text-center"><?= isset($model->checked_at) ? Yii::$app->thaiFormatter->asDate($model->checked_at, 'php:d/m/Y') : '' ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= isset($lastYearForm->checked_at) ? Yii::$app->thaiFormatter->asDate($lastYearForm->checked_at, 'php:d/m/Y') : '' ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">สถานะ</td>
            <td class="bg-green-600 white text-center"><?= $model->statusBadge ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= $lastYearForm->statusBadge ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td class="font-weight-900">หมายเหตุการตรวจสอบ</td>
            <td class="bg-green-600 white text-center"><?= $model->comment ?></td>
            <?php if (isset($lastYearForm)) : ?>
                <td class="text-center"><?= $lastYearForm->comment ?></td>
            <?php endif; ?>
        </tr>
    </tbody>
</table>
<?php
$css = <<<cs
    th {
        font-weight: 900;
    }
cs;
$this->registerCss($css);

views/monthly-form-submit/_search-check-list.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use kartik\form\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Office;
use app\models\Role;
use app\models\Setting;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\MonthlyFormSubmit */
/* @var $form yii\widgets\ActiveForm */
$currentRole = Yii::$app->session->get('currentRole');
?>

<div class="monthly-form-submit-search margin-bottom-10">

    <?php
    $form = ActiveForm::begin([
                'action' => Url::to(['monthly-form-submit/check-list']),
                'method' => 'get',
                'options' => [
                    'data-pjax' => 1,
                ],
                'type' => ActiveForm::TYPE_INLINE,
    ]);
    ?>

    <?php
    // Usage with ActiveForm and model
//    if ($currentRole['role_id'] == Role::SUPER_ADMINISTRATOR) {
//        $level = Setting::getValue(Setting::SUPER_ADMIN_CHECK_LEVEL);
//        $data = ArrayHelper::map(Office::find()->isDeleted(false)->level("<={$level}")->orderBy('CONVERT(office.name USING TIS620) ASC')->all(), 'id', 'name');
//    } else {
//        $data = ArrayHelper::map(Office::find()->isDeleted(false)->parent(Yii::$app->user->identity->person->office_id)->orderBy('CONVERT(office.name USING TIS620) ASC')->all(), 'id', 'name');
//    }
    $data = ArrayHelper::map(Yii::$app->user->identity->person->getTotalResponsibleOffices(), 'id', 'typeName');

//    \yii\helpers\VarDumper::dump($data, 10, TRUE);
    echo $form->field($model, 'office_id', [
        'options' => [
            'style' => 'width: 300px',
            'class' => 'form-group',
        ]
    ])->widget(Select2::classname(), [
        'data' => $data,
        'options' => ['placeholder' => 'หน่วยงาน'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

    <?= $form->field($model, 'year')->textInput(['type' => 'number','style'=>'width: 100px']); ?>

    <?=
    $form->field($model, 'month', [
        'options' => [
            'style' => 'width: 150px',
            'class' => 'form-group',
        ]
    ])->widget(Select2::classname(), [
        'data' => Yii::$app->util->monthNames,
        'options' => ['placeholder' => 'เดือน'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

    <?php
    if ($currentRole['role_id'] == Role::SUPER_ADMINISTRATOR || $currentRole['role_id'] == Role::REVIEWER) {
        $data = ArrayHelper::map(\app\models\OfficeType::find()->orderBy('CONVERT(office_type.name USING TIS620) ASC')->all(), 'id', 'name');
//    \yii\helpers\VarDumper::dump($data, 10, TRUE);
        echo $form->field($model, 'officeType')->dropDownList($data, ['prompt' => 'ประเภทหน่วยงาน']);

        echo $form->field($model, 'level')->dropDownList(Yii::$app->util->getLevelLabels(), ['prompt' => 'ระดับหน่วยงาน']);
    }
    ?>

    <div class="form-group">
    <?= Html::submitButton(Yii::t('app', 'ค้นหา'), ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

</div>

views/monthly-form-submit/_search.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MonthlyFormSubmit */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="monthly-form-submit-search">

    <?php $form = ActiveForm::begin([
        'action' => Url::to(['monthly-form-submit/index']),
        'method' => 'get',
        'options' => [
            'data-pjax' => 1,
        ],
        'type' => ActiveForm::TYPE_INLINE,
    ]); ?>
    
    <?= $form->field($model, 'office_id') ?>

    <?= $form->field($model, 'source_type_id') ?>

    <?= $form->field($model, 'year') ?>

    <?= $form->field($model, 'month') ?>

    <?= $form->field($model, 'office_population') ?>

    <?= $form->field($model, 'work_day') ?>

    <?= $form->field($model, 'garbage') ?>

    <?= $form->field($model, 'bag') ?>

    <?= $form->field($model, 'cup') ?>

    <?= $form->field($model, 'foam') ?>

    <?= $form->field($model, 'ref_id') ?>

    <?= $form->field($model, 'remark') ?>

    <?= $form->field($model, 'submitted_by') ?>

    <?= $form->field($model, 'submitted_at') ?>

    <?= $form->field($model, 'confirmed_by') ?>

    <?= $form->field($model, 'confirmed_at') ?>

    <?= $form->field($model, 'checked_by') ?>

    <?= $form->field($model, 'checked_at') ?>

    <?= $form->field($model, 'is_pass') ?>

    <?= $form->field($model, 'deleted') ?>

    <?= $form->field($model, 'created_by') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_by') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?= $form->field($model, 'pop_ext') ?>

    <?= $form->field($model, 'pop_int') ?>

  
	<div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'ค้นหา'), ['class' => 'btn btn-primary']) ?>
        </div>

    <?php ActiveForm::end(); ?>
    
</div>

views/monthly-form-submit/check.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MonthlyFormSubmit */
?>
<div class="monthly-form-submit-check">

    <?= $this->renderFile('@app/views/widgets/_alert.php'); ?>

    <?=
    $this->renderFile('@app/views/monthly-form-submit/view.php', [
        'model' => $model,
        'redirect' => Url::to(['monthly-form-submit/check', 'id' => $model->id, 'file' => 1], true),
        'file' => isset($file) ? $file : null,
        'from' => 'check',
    ]);
    ?>
    <div class="monthly-form-submit-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'is_pass')->radioList(Yii::$app->util->getPassFailLabels()) ?>

        <?= $form->field($model, 'comment')->textarea(); ?>

        <?php if (!Yii::$app->request->isAjax) { ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'บันทึก'), ['class' => 'btn btn-primary']) ?>
            </div>
        <?php } ?>

        <?php ActiveForm::end(); ?>

    </div>


</div>